Repository hoprnet/hopr-core, pull requests merged in 2020-07, with the labels that each got.

#149 🔖 Core v0.6.17 Release
  package.json
Labels: Minor Version, merge when passing

#150 🔖 Chat v1.1.5-dev Release
  chat/package.json
  chat/yarn.lock
Labels: merge when passing

#151 🔖 Chat v1.1.5-dev.2f63576 Release
  chat/.env
  chat/package.json
Labels: merge when passing

#152 🔖 Chat v1.1.6-dev.65e3d09 Release
  chat/package.json
  chat/yarn.lock
Labels: merge when passing

#153 🔖 Chat v1.1.6-dev.c992f25 Release
  chat/.env
Labels: merge when passing

#174 Feature/manage relay state
  package.json
  src/network/transport/constants.ts
  src/network/transport/index.spec.ts
  src/network/transport/index.ts
  src/network/transport/listener.ts
  src/network/transport/relay.spec.ts
  src/network/transport/relay.ts
  yarn.lock
Labels: Patch Version

#240 crawling fixes
  chat/package.json
  chat/yarn.lock
  package.json
  src/interactions/network/crawler.ts
  src/network/crawler.spec.ts
  src/network/crawler.ts
Labels: Patch Version

#246 🔖 Chat 1.2.0
  chat/index.ts
  chat/package.json
  chat/yarn.lock
Labels: merge when passing

#247 🔖 Chat 1.2.0-develop
  chat/.env
  chat/.env.develop
  chat/package.json
Labels: merge when passing
